# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

setup_ci

default_platform(:macos)

platform :macos do
  desc "Sync development signing certificates"
  lane :sync_dev do
    sync_code_signing(
      type: "development",
      git_private_key: ENV["APPLE_CERTIFICATES_SSH_KEY"],
      skip_provisioning_profiles: true
    )
  end
  desc "Sync distribution signing certificates"
  lane :sync_dist do
    sync_code_signing(
      type: "appstore",
      git_private_key: ENV["APPLE_CERTIFICATES_SSH_KEY"],
      skip_provisioning_profiles: true
    )
  end
end
