title: Twake
contents:
  - x: 448
    y: 344
    type: link
    path: "/Applications"
  - x: 192
    y: 344
    type: file
    path: "Twake.app"
code-sign:
  signing-identity: "Developer ID Application: Linagora"
